### ISSUE TITLE
1.6.2 Cannot create listener error

### ISSUE THREAD

**Issue by 8bitter** [tbm98/flutter-riverpod-live-templates#5]
I'm seeing an exception in the IDE Fatal Errors window:

com.intellij.diagnostic.PluginException: Cannot create listener com.github.tbm98.flutterriverpodsnippets.listeners.MyProjectManagerListener [Plugin: org.tbm98.flutter-riverpod-snippets]
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:788)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.java:187)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.java:157)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.java:360)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.java:151)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.lambda$publish$0(MessageBusImpl.java:196)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.publish(MessageBusImpl.java:196)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy72.projectOpened(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$1.run(ProjectManagerExImpl.kt:336)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:476)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.github.tbm98.flutterriverpodsnippets.listeners.MyProjectManagerListener PluginClassLoader[PluginDescriptor(name=Flutter Riverpod Snippets, id=org.tbm98.flutter-riverpod-snippets, path=/home/kkiyohara/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57.plugins/flutter-riverpod-snippets, version=1.6.2)] com.intellij.ide.plugins.cl.PluginClassLoader@2f7ec513
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:785)
	... 40 more

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021
Licensed to Keith Kiyohara
You have a perpetual fallback license for this version.
Subscription is active until January 22, 2022.
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-136-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: cn.neday.excavator, org.tbm98.flutter-riverpod-snippets, com.dubreuia, Dart, io.flutter, de.mariushoefler.flutter_enhancement_suite, org.jetbrains.kotlin, Pythonid
Current Desktop: ubuntu:GNOME

**Comment by tbm98** [comment]
I will fix soon. Thanks for your feedback

**Comment by tbm98** [comment]
Hi @8bitter,
Can you download the latest at [here](https://github.com/tbm98/flutter-riverpod-live-templates/releases/download/v1.6.3/flutter-riverpod-snippets-1.6.3.zip) and feedback to me?

**Comment by 8bitter** [comment]
I was able to install what you sent and it seems to be working. But I'd
point out that the released version was inconsistent in crashes. On some
startups it would crash, but on others it worked fine. Not sure why since I
keep relaunching with the same project.

Thanks for your quick response!

**Comment by tbm98** [comment]
I think problem is your version ide. It is ultimate, I have built plugin
from community version 🤔

Vào 9:31, Th 4, 17 thg 3, 2021 8bitter ***@***.***> đã viết:

> I was able to install what you sent and it seems to be working. But I'd
> point out that the released version was inconsistent in crashes. On some
> startups it would crash, but on others it worked fine. Not sure why since I
> keep relaunching with the same project.
>
> Thanks for your quick response!
>
